config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  get  'posts',     to: 'posts#index'
  get  'posts/new'
  post 'posts',     to: 'posts#create'
  get  'posts/:id', to: 'posts#show', as: 'posts_show'

  get  'users/:username', to: 'users#profile', as: 'profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :photo, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates :photo, attachment_presence: true
  validates :description, presence: true

  belongs_to :user

  def self.latest(num)
    order(created_at: :desc).limit(num)
  end

  after_save do
    PostMailer.congrats(user).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts

  # Virtual fields
  def name
    "#{firstname} #{lastname}"
  end

  # getProfile
  def self.getProfile(username)
    find_by(username: username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :firstname, :lastname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :firstname, :lastname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.latest(10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save 
      redirect_to posts_path, notice: 'The post was successfully created'
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private
    def post_params
      params.require(:post).permit(:photo, :description, :location)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.getProfile(params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(type)
      case type
        when :success then "success"
        when :error   then "danger"
        when :alert   then "warning"
        when :notice  then "info"
        else "info"
      end
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Makeitgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to 'Makeitgram', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Create a post', posts_new_path, class: 'nav-link' %>
          </li>
        <% end %>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.username, edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link', method: :delete %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <div class="wrapper">
            <% flash.each do |type, message| %>
            <div class="alert alert-<%= flash_class type %> alert-dismissible fade show" role="alert">
              <%= message %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post__header">
    <p><%= link_to item.user.username, profile_path(item.user.username) %></p>
  </div>
  <div class="post__photo">
    <% if show_link %>
      <%= link_to posts_show_path(item.id) do %>
      <%= image_tag item.photo.url %>
      <% end %>
    <% else %>
      <%= image_tag item.photo.url %>
    <% end %>
  </div>
  <div class="post__body">
    <div class="post__description">
      <%= item.description %>
    </div>
    <div class="post__published">
      <%= time_ago_in_words item.created_at %>
    </div>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= render partial: 'post', locals: { item: post, show_link: true } %>
<% end %>

app/views/posts/new.html.erb
<% if @post.errors.full_messages.any? %>
<div class="errors_full_messages">
  <p>The form contains <%= @post.errors.full_messages.size %> error(s)</p>
  <ul>
  <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for @post do |form| %>
  <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "form-control-file" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class:"form-control" %>
  </div>
  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<%= render partial: 'post', locals: { item: @post, show_link: false } %>

app/views/users/profile.html.erb
<h1><%= @user.name %></h1>
<p>@<%= @user.username %></p>

<% @user.posts.each do |post| %>
<%= render partial: 'posts/post', locals: { item: post, show_link: true } %>
<% end %>